---
- hosts: localhost
  become: yes
  remote_user: devops
  tasks:
   - block:
       - name: copy the config file1
         copy:
          src: /tmp/myapp1.conf
          dest: /etc/myapp1.conf
          owner: student
          mode: 0644
     rescue:
       - debug:
           msg: "The copy of app config file failed"       
     always:      
       - debug:
           msg: "this is to be executed always, no matter what"
