---
- hosts: localhost
  become: yes
  remote_user: devops
  tasks:
   - name: copy the config file
     copy:
       src: /tmp/myapp.conf
       dest: /etc/myapp.conf
     notify:
        - restart-myapp
  handlers:
   - name: restart-myapp
     debug:
       msg: "restart-myapp"      
