---
- hosts: localhost
  become: yes
  remote_user: devops
  tasks:
   - name: copy the config file1
     copy:
       src: /tmp/myapp1.conf
       dest: /etc/myapp1.conf
     notify:
        - restart-myapp1
   - meta: flush_handlers
   - name: copy the config file2
     copy:
       src: /tmp/myapp2.conf
       dest: /etc/myapp2.conf
     notify:
        - restart-myapp2
  handlers:
   - name: restart-myapp2
     debug:
       msg: "restart-myapp2"      
   - name: restart-myapp1
     debug:
       msg: "restart-myapp1"      
