---
- name: Demonstrate the "in" keyword
  hosts: serverc
  become: true
  remote_user: devops
  gather_facts: yes
  vars:
    supported_distros:
      - RedHat
      - Fedora
  tasks:
   - name: Install httpd using yum, where supported
     yum:
       name: httpd
       state: present
       # when: ansible_distribution in supported_distros
     when: ansible_distribution == "RedHat" or ansible_distribution == "Fedora"
